# Generated by Django 5.0.7 on 2024-08-18 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_apellidos_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(800)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permiso_u',
            field=models.CharField(choices=[('admin', 'Admin'), ('estudiante', 'Estudiante'), ('docente', 'Docente'), ('empresa', 'Empresa')], default='admin', max_length=20),
        ),
    ]
