# Generated by Django 5.0.7 on 2024-09-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_evento_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='categorias_preferidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='api.categoriaevento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='categorias',
            field=models.ManyToManyField(related_name='eventos', to='api.categoriaevento'),
        ),
    ]
