# Generated by Django 5.0.7 on 2024-09-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_categoriaevento_customuser_categorias_preferidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria_p',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
