# Generated by Django 5.0.7 on 2024-09-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_evento_fecha_evento_evento_fecha_fin_beneficio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaevento',
            name='tipo_e',
            field=models.CharField(choices=[('evento', 'Evento'), ('practica', 'Práctica'), ('beneficio', 'Beneficio'), ('descuento', 'Descuento')], default='evento', max_length=10),
        ),
    ]
