# Generated by Django 5.0.7 on 2024-09-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_evento_fecha_fin_descuento_alter_customuser_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ayuda_economica_p',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='direccion_practica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin_practica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='horas_practica',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='telefono_practica',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
