# Generated by Django 5.0.7 on 2024-09-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_evento_ayuda_economica_p_evento_direccion_practica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='baneo',
            field=models.BooleanField(default=False),
        ),
    ]
