# Generated by Django 5.0.7 on 2024-09-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customuser_permiso_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='acceso_e',
            field=models.CharField(choices=[('publico', 'Público'), ('red-universitaria', 'Red Universitaria')], default='red-universitaria', max_length=20),
        ),
    ]
